# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hdfs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hdfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhdfs.proto\x12\x04hdfs\"+\n\rUploadRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"2\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x0f\x44ownloadRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"B\n\x10\x44ownloadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1b\n\x0bListRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"0\n\x0cListResponse\x12\x0f\n\x07\x65ntries\x18\x01 \x03(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xac\x01\n\x0bHdfsService\x12\x33\n\x06Upload\x12\x13.hdfs.UploadRequest\x1a\x14.hdfs.UploadResponse\x12\x39\n\x08\x44ownload\x12\x15.hdfs.DownloadRequest\x1a\x16.hdfs.DownloadResponse\x12-\n\x04List\x12\x11.hdfs.ListRequest\x1a\x12.hdfs.ListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hdfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=20
  _globals['_UPLOADREQUEST']._serialized_end=63
  _globals['_UPLOADRESPONSE']._serialized_start=65
  _globals['_UPLOADRESPONSE']._serialized_end=115
  _globals['_DOWNLOADREQUEST']._serialized_start=117
  _globals['_DOWNLOADREQUEST']._serialized_end=148
  _globals['_DOWNLOADRESPONSE']._serialized_start=150
  _globals['_DOWNLOADRESPONSE']._serialized_end=216
  _globals['_LISTREQUEST']._serialized_start=218
  _globals['_LISTREQUEST']._serialized_end=245
  _globals['_LISTRESPONSE']._serialized_start=247
  _globals['_LISTRESPONSE']._serialized_end=295
  _globals['_HDFSSERVICE']._serialized_start=298
  _globals['_HDFSSERVICE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
