services:
  hdfs:
    build: ./hdfs
    container_name: hdfs
    ports:
      - "50051:50051"
    volumes:
      - ./hdfs_data:/data
  
  boss:
    build: ./boss
    container_name: boss
    depends_on:
      - hdfs
    ports:
      - "50052:50052"
  
  worker1:
    build: ./worker
    container_name: worker1
    environment:
      - WORKER_ID=1
      - BOSS_URL=http://boss:8080
      - HDFS_ADDR=hdfs:50051
    ports:
      - "8081:8080"

  worker2:
    build: ./worker
    container_name: worker2
    environment:
      - WORKER_ID=2
      - BOSS_URL=http://boss:8080
      - HDFS_ADDR=hdfs:50051
    ports:
      - "8082:8080"

  worker3:
    build: ./worker
    container_name: worker3
    environment:
      - WORKER_ID=3
      - BOSS_URL=http://boss:8080
      - HDFS_ADDR=hdfs:50051
    ports:
      - "8083:8080"

  worker4:
    build: ./worker
    container_name: worker4
    environment:
      - WORKER_ID=4
      - BOSS_URL=http://boss:8080
      - HDFS_ADDR=hdfs:50051
    ports:
      - "8084:8080"