FROM python:3.9-slim

WORKDIR /app

RUN pip install grpcio grpcio-tools numpy

COPY map_reduce.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. map_reduce.proto

COPY scheduler.py .
COPY server.py .

EXPOSE 5440
CMD ["python3", "server.py"]
