FROM python:3.9-slim

WORKDIR /app

RUN pip install grpcio grpcio-tools pandas pyarrow

COPY map_reduce.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. map_reduce.proto

COPY dataset_generator.py .
COPY client.py .

CMD ["python3", "client.py"]
