FROM python:3.9-slim

WORKDIR /app

# Add dependencies for your boss node here
# e.g. RUN pip install ...

# You will need to add your boss application code.
# e.g. COPY boss.py .
# CMD ["python", "boss.py"]
