FROM python:3.9-slim

WORKDIR /app

# Install Java (required for PyArrow HDFS access)
RUN apt-get update && apt-get install -y openjdk-11-jdk && rm -rf /var/lib/apt/lists/*

RUN pip install grpcio grpcio-tools pandas pyarrow

COPY boss.proto .
COPY map_reduce.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. boss.proto
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. map_reduce.proto

COPY boss.py .

EXPOSE 50052
CMD ["python", "boss.py"]
