FROM mapreduce-hdfs

# Copy proto file and generate gRPC code
COPY map_reduce.proto ./
RUN python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. map_reduce.proto

# Copy master code
COPY master.py ./

# Find HDFS and start master (unbuffered for real-time logging)
CMD export CLASSPATH=`$HADOOP_HOME/bin/hdfs classpath --glob` && python3 -u master.py

