FROM python:3.9-slim

WORKDIR /app

# Install Java (required for PyArrow HDFS access)
RUN apt-get update && apt-get install -y default-jdk && rm -rf /var/lib/apt/lists/*

RUN pip install grpcio grpcio-tools pandas pyarrow numpy matplotlib

COPY map_reduce.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. map_reduce.proto

COPY dataset_generator.py .
COPY client.py .
COPY create_test_data.py .
COPY benchmark.py .
COPY plot_results.py .

CMD ["python3", "client.py"]
