FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    wget curl openjdk-11-jdk python3-pip iproute2 nano \
    && rm -rf /var/lib/apt/lists/*

# Download and install Hadoop
RUN wget https://dlcdn.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz && \
    tar -xf hadoop-3.3.6.tar.gz && \
    rm hadoop-3.3.6.tar.gz && \
    mv hadoop-3.3.6 /hadoop

# Set environment variables
ENV HADOOP_HOME=/hadoop
ENV PATH="${PATH}:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin"
ENV HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop

# Create startup script that finds Java dynamically
RUN echo '#!/bin/bash\n\
set -e\n\
\n\
# Find Java dynamically\n\
JAVA_PATH=$(readlink -f $(which java))\n\
export JAVA_HOME=$(echo ${JAVA_PATH} | sed "s:/bin/java::")\n\
echo "Found JAVA_HOME: $JAVA_HOME"\n\
\n\
# Set JAVA_HOME in hadoop-env.sh\n\
echo "export JAVA_HOME=$JAVA_HOME" >> ${HADOOP_CONF_DIR}/hadoop-env.sh\n\
\n\
# Create core-site.xml\n\
cat > ${HADOOP_CONF_DIR}/core-site.xml <<EOF\n\
<?xml version="1.0"?>\n\
<configuration>\n\
  <property>\n\
    <name>fs.defaultFS</name>\n\
    <value>hdfs://nn:9000</value>\n\
  </property>\n\
  <property>\n\
    <name>hadoop.tmp.dir</name>\n\
    <value>/tmp/hadoop</value>\n\
  </property>\n\
</configuration>\n\
EOF\n\
\n\
# Create hdfs-site.xml\n\
cat > ${HADOOP_CONF_DIR}/hdfs-site.xml <<EOF\n\
<?xml version="1.0"?>\n\
<configuration>\n\
  <property>\n\
    <name>dfs.replication</name>\n\
    <value>1</value>\n\
  </property>\n\
  <property>\n\
    <name>dfs.namenode.name.dir</name>\n\
    <value>file:///hadoop/dfs/name</value>\n\
  </property>\n\
  <property>\n\
    <name>dfs.datanode.data.dir</name>\n\
    <value>file:///hadoop/dfs/data</value>\n\
  </property>\n\
  <property>\n\
    <name>dfs.namenode.http-address</name>\n\
    <value>0.0.0.0:9870</value>\n\
  </property>\n\
  <property>\n\
    <name>dfs.permissions.enabled</name>\n\
    <value>false</value>\n\
  </property>\n\
</configuration>\n\
EOF\n\
\n\
# Create directories\n\
mkdir -p /hadoop/dfs/name /hadoop/dfs/data /tmp/hadoop\n\
\n\
# Format namenode if not already formatted\n\
if [ ! -d "/hadoop/dfs/name/current" ]; then\n\
  echo "Formatting namenode..."\n\
  hdfs namenode -format -force -nonInteractive\n\
fi\n\
\n\
# Start datanode in background\n\
echo "Starting HDFS datanode..."\n\
hdfs datanode &\n\
\n\
# Give datanode time to start\n\
sleep 5\n\
\n\
# Start namenode\n\
echo "Starting HDFS namenode..."\n\
exec hdfs namenode' > /start-hdfs.sh && chmod +x /start-hdfs.sh

# Expose ports
EXPOSE 9000 9870

CMD ["/start-hdfs.sh"]