name: ${PROJECT}

services:
  scheduler:
    image: ${PROJECT}-scheduler
    hostname: scheduler
    deploy:
      resources:
        limits:
          memory: 3g
    ports:
      - "5440:5440"
    networks:
      - mapreduce-net

  boss:
    image: ${PROJECT}-boss
    hostname: boss
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - "50052:50052"
    depends_on:
      - scheduler
    networks:
      - mapreduce-net

  worker1:
    image: ${PROJECT}-worker
    hostname: worker1
    environment:
      - WORKER_ID=worker-1
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"
    depends_on:
      - boss
    networks:
      - mapreduce-net

  worker2:
    image: ${PROJECT}-worker
    hostname: worker2
    environment:
      - WORKER_ID=worker-2
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"
    depends_on:
      - boss
    networks:
      - mapreduce-net

  worker3:
    image: ${PROJECT}-worker
    hostname: worker3
    environment:
      - WORKER_ID=worker-3
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"
    depends_on:
      - boss
    networks:
      - mapreduce-net

  worker4:
    image: ${PROJECT}-worker
    hostname: worker4
    environment:
      - WORKER_ID=worker-4
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"
    depends_on:
      - boss
    networks:
      - mapreduce-net

  hdfs:
    image: p4-hdfs
    hostname: nn
    command: sleep infinity
    ports:
      - "9870:9870"
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - mapreduce-net

  client:
    image: ${PROJECT}-client
    depends_on:
      - scheduler
    networks:
      - mapreduce-net

networks:
  mapreduce-net:
    driver: bridge
