FROM mapreduce-hdfs

# Copy proto file and generate gRPC code
COPY map_reduce.proto ./
RUN python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. map_reduce.proto

# Copy worker code and user functions
COPY worker.py ./
COPY user_funcs/ ./user_funcs/

# Find HDFS and start worker
CMD export CLASSPATH=`$HADOOP_HOME/bin/hdfs classpath --glob` && python3 worker.py
