# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map_reduce.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'map_reduce.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10map_reduce.proto\"\xb4\x01\n\x12ScheduleJobRequest\x12\x14\n\x0c\x64\x61taset_path\x18\x01 \x01(\t\x12\x16\n\x0enum_partitions\x18\x02 \x01(\x05\x12\x19\n\x11map_function_path\x18\x03 \x01(\t\x12\x1c\n\x14reduce_function_path\x18\x04 \x01(\t\x12\x1d\n\x15repartition_threshold\x18\x05 \x01(\x01\x12\x18\n\x10\x63ustom_hash_func\x18\x06 \x01(\t\"%\n\x13GetJobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"M\n\tJobStatus\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0boutput_path\x18\x03 \x01(\t\x12\x0b\n\x03\x65rr\x18\x04 \x01(\t2k\n\tScheduler\x12,\n\tSubmitJob\x12\x13.ScheduleJobRequest\x1a\n.JobStatus\x12\x30\n\x0cGetJobStatus\x12\x14.GetJobStatusRequest\x1a\n.JobStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_reduce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULEJOBREQUEST']._serialized_start=21
  _globals['_SCHEDULEJOBREQUEST']._serialized_end=201
  _globals['_GETJOBSTATUSREQUEST']._serialized_start=203
  _globals['_GETJOBSTATUSREQUEST']._serialized_end=240
  _globals['_JOBSTATUS']._serialized_start=242
  _globals['_JOBSTATUS']._serialized_end=319
  _globals['_SCHEDULER']._serialized_start=321
  _globals['_SCHEDULER']._serialized_end=428
# @@protoc_insertion_point(module_scope)
