# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mapreduce.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mapreduce.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapreduce.proto\x12\tmapreduce\"~\n\nJobRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\x12\x16\n\x0euser_code_path\x18\x03 \x01(\t\x12\x15\n\rnum_map_tasks\x18\x04 \x01(\x05\x12\x18\n\x10num_reduce_tasks\x18\x05 \x01(\x05\"?\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\"\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"D\n\x11JobStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\x99\x01\n\x10MapReduceService\x12:\n\tSubmitJob\x12\x15.mapreduce.JobRequest\x1a\x16.mapreduce.JobResponse\x12I\n\x0cGetJobStatus\x12\x1b.mapreduce.JobStatusRequest\x1a\x1c.mapreduce.JobStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapreduce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOBREQUEST']._serialized_start=30
  _globals['_JOBREQUEST']._serialized_end=156
  _globals['_JOBRESPONSE']._serialized_start=158
  _globals['_JOBRESPONSE']._serialized_end=221
  _globals['_JOBSTATUSREQUEST']._serialized_start=223
  _globals['_JOBSTATUSREQUEST']._serialized_end=257
  _globals['_JOBSTATUSRESPONSE']._serialized_start=259
  _globals['_JOBSTATUSRESPONSE']._serialized_end=327
  _globals['_MAPREDUCESERVICE']._serialized_start=330
  _globals['_MAPREDUCESERVICE']._serialized_end=483
# @@protoc_insertion_point(module_scope)
